name = "blupack"
author = "Infernity"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b15e15968b14d64aada5faee47cc0aee58fd901f95147f329f02a8b40b14e9f"

[versions]
forge = "40.1.51"
minecraft = "1.18.2"
